version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express-test
    restart: always
    ports:
      - "8081:8081"

  projetoapi:
    image: lscudeler/app-mongodb:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo


